In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
df["Age"] = df["Age"].fillna(df["Age"].median())
#df.fillna(df.median(numeric_only=True),inplace=True)

In [5]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
# Cabin (special case)
df["Cabin"] = df["Cabin"].fillna("Unknown")

#df.fillna(df.mode().iloc[0],inplace=True)

In [6]:
df.columns=df.columns.str.lower() 
df=df.apply(lambda x:x.str.strip() if x.dtype=="object" else x)

In [7]:
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Unknown,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Unknown,S

In [9]:
df["sex"]=df["sex"].map({"male":0,"female":1})

In [10]:
df=df.drop_duplicates(subset=["name","age","ticket"])

In [11]:
num_cols=df.select_dtypes(include=np.number).columns 

for col in num_cols: 
    Q1=df[col].quantile(0.25) 
    Q3=df[col].quantile(0.75) 
    IQR=Q3-Q1 

    lower=Q1 - 1.5*IQR 
    upper=Q3 + 1.5*IQR 

    df[col]=np.where(df[col]<lower,lower,df[col])
    df[col]=np.where(df[col]>upper,upper,df[col]) 

    # Save cleaned data 
    df.to_csv("cleaned_titanic.csv",index=False)

In [12]:
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1.0,0.0,3.0,"Braund, Mr. Owen Harris",NaN,22.0,1.0,0.0,A/5 21171,7.2500,Unknown,S
1,2.0,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",NaN,38.0,1.0,0.0,PC 17599,65.6344,C85,C
2,3.0,1.0,3.0,"Heikkinen, Miss. Laina",NaN,26.0,0.0,0.0,STON/O2. 3101282,7.9250,Unknown,S
3,4.0,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",NaN,35.0,1.0,0.0,113803,53.1000,C123,S
4,5.0,0.0,3.0,"Allen, Mr. William Henry",NaN,35.0,0.0,0.0,373450,8.0500,Unknown,S